<?php

namespace AppBundle\Repository;

/**
 * SeminaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeminaireRepository extends \Doctrine\ORM\EntityRepository
{
}
